name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Copy Data
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        source: "src/assets/,src/index.html,src/styles.css,src/favicon.ico"
        target: "${{ secrets.WEBSITE_DIR }}/"